# Generated by Django 5.2.1 on 2025-11-03 08:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_role_staff_role_api_role_name_7b16d4_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tag",
            name="profile",
            field=models.ForeignKey(
                blank=True,
                help_text="Organization profile this tag belongs to",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tags",
                to="api.profile",
            ),
        ),
        migrations.AlterField(
            model_name="tag",
            name="tag",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
