# Generated by Django 5.2.1 on 2025-11-03 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_tag_profile_alter_tag_tag"),
    ]

    operations = [
        migrations.CreateModel(
            name="Schedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "schedule_banner",
                    models.ImageField(
                        blank=True, null=True, upload_to="schedule_banners"
                    ),
                ),
                ("genre", models.CharField(blank=True, max_length=255, null=True)),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("description", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedules",
                        to="api.event",
                    ),
                ),
            ],
            options={
                "ordering": ["start_time"],
            },
        ),
    ]
