# Generated by Django 5.2.1 on 2025-11-03 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_schedule"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="event_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("technical", "Technical"),
                    ("Outreach", "Outreach"),
                    ("Indoor", "Indoor"),
                ],
                max_length=255,
                null=True,
            ),
        ),
    ]
