# Generated by Django 5.2.1 on 2025-11-05 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_alter_event_event_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="attendance",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="event_category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Music Festival", "Music Festival"),
                    ("Outreach", "Outreach"),
                    ("Indoor", "Indoor"),
                ],
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="event_type",
            field=models.CharField(
                blank=True,
                choices=[("Social Pull", "social"), ("Events", "events")],
                max_length=255,
                null=True,
            ),
        ),
    ]
