# Generated by Django 5.2.1 on 2025-11-05 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_event_attendance_event_event_category_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="event_type",
            field=models.CharField(
                blank=True,
                choices=[("Social_Pull", "social"), ("Events", "events")],
                max_length=255,
                null=True,
            ),
        ),
    ]
