# Generated by Django 5.2.1 on 2025-11-05 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0010_alter_event_event_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="event_type",
            field=models.CharField(
                blank=True,
                choices=[("Social_Pull", "Social Pull"), ("Events", "Events")],
                max_length=255,
                null=True,
            ),
        ),
    ]
