# Generated by Django 5.2.1 on 2025-11-05 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0012_alter_event_event_category_alter_event_event_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="event_category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Outdoor & Hiking", "Outdoor & Hiking"),
                    ("Live Music", "Live Music"),
                    ("Sports & Fitness", "Sports & Fitness"),
                    ("Nightlife", "Nightlife"),
                    ("Festivals", "Festivals"),
                    ("Theatre & Shows", "Theatre & Shows"),
                    ("Art & Culture", "Art & Culture"),
                    ("Food & Drink", "Food & Drink"),
                ],
                max_length=255,
                null=True,
            ),
        ),
    ]
